[package]
name = "fast_emu_gui"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1"
serde_yaml = "0.9"
eframe = "0.31.1"
crossbeam = "0.8.4"
once_cell = "1.21.3"

[dependencies.libc]
version = "0.2"
